/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentservices;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;


public class Campuses extends javax.swing.JFrame {
     Connection con; //establish connection
    PreparedStatement statement; //execute sql statement more of optimised
    Statement st;//execute sql statement less of optimised
    String cs; //holding path of the database
    String user;//username for the database
    String password;//password for the database
    String query;
    ResultSet rs;
    String records;
    Boolean bnext = false;
    Boolean bprevious = true;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Campuses.class.getName());

    /**
     * Creates new form Campuses
     */
    public Campuses() {
        initComponents();
        
         con = null;
        st = null;
        statement = null;

        cs = "jdbc:mysql://localhost:3306/studentservicesdb";
        user = "root";
        password = "Peacebewithyouall2020!!";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        campusnametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campusidtxt = new javax.swing.JTextField();
        Findbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        Firstbtn = new javax.swing.JButton();
        Lastbtn = new javax.swing.JButton();
        Nextbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Previousbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Campus Name");

        jLabel3.setText("Campus ID");

        Findbtn.setText("Find");
        Findbtn.addActionListener(this::FindbtnActionPerformed);

        savebtn.setText("Save");
        savebtn.addActionListener(this::savebtnActionPerformed);

        Firstbtn.setText("First");
        Firstbtn.addActionListener(this::FirstbtnActionPerformed);

        Lastbtn.setText("Last");
        Lastbtn.addActionListener(this::LastbtnActionPerformed);

        Nextbtn.setText("Next");
        Nextbtn.addActionListener(this::NextbtnActionPerformed);

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(this::DeletebtnActionPerformed);

        Previousbtn.setText("Previous");
        Previousbtn.addActionListener(this::PreviousbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(campusnametxt)
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(savebtn)
                .addGap(18, 18, 18)
                .addComponent(Findbtn)
                .addGap(18, 18, 18)
                .addComponent(Firstbtn)
                .addGap(18, 18, 18)
                .addComponent(Lastbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nextbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Previousbtn)
                .addGap(18, 18, 18)
                .addComponent(Deletebtn)
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(479, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(campusidtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addGap(190, 190, 190)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Findbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Firstbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lastbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Previousbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(campusidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindbtnActionPerformed
        // TODO add your handling code here:
    String campusName = campusnametxt.getText().trim();

    if (campusName.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Type a Campus Name to search for");
        return;
    }

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(cs, user, password);

        PreparedStatement pst = con.prepareStatement(
                "SELECT * FROM Campuses WHERE Campus_name = ?",
                ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
        pst.setString(1, campusName);
        ResultSet rs = pst.executeQuery();

        if (rs.first()) {
            campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
        } else {
            JOptionPane.showMessageDialog(null, "Record not found");
            campusidtxt.setText("");
            campusnametxt.setText(campusName);
            campusnametxt.requestFocus();
        }

        rs.close();
        pst.close();

    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    } finally {
        try {
            if (con != null) {
                con.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    }//GEN-LAST:event_FindbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        int s1 = Integer.parseInt(campusidtxt.getText());
        String s2 = campusnametxt.getText();

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");//register JDBC driver

            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();
            query = "INSERT INTO Campuses (Campus_id,Campus_name) VALUES ('" + s1 + "','" + s2 + "')";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Campus saved successfully");

            campusidtxt.setText("");
            campusnametxt.setText("");

            campusidtxt.requestFocus();
        } catch (SQLException ex) {
            ex.printStackTrace();//displays information about SQL statement incase you typed table name or field name that is not existing
            //it displays where the error may be
        } catch (ClassNotFoundException e) {
            e.printStackTrace();  //checks if the driver  is not configured
        } finally {

            try {
                if (st != null) {
                    st.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void FirstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstbtnActionPerformed
        // TODO add your handling code here:
        
    // TODO add your handling code here:

    try {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection(cs, user, password);
        st = con.createStatement();

        PreparedStatement st = con.prepareStatement("SELECT * FROM Campuses",
                ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        ResultSet rs = st.executeQuery();

        if (rs.first()) {
            campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));

        } else {
            JOptionPane.showMessageDialog(null, "Record not found");
            campusnametxt.setText("");
            campusnametxt.requestFocus();
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    } finally {

        try {
            if (st != null) {
                st.close();
            }
            if (con != null) {
                con.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
 
    }//GEN-LAST:event_FirstbtnActionPerformed

    private void LastbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastbtnActionPerformed
        // TODO add your handling code here:
        
     // TODO add your handling code here:
    try {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection(cs, user, password);
        st = con.createStatement();
        PreparedStatement st = con.prepareStatement("SELECT * FROM Campuses",
                ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        ResultSet rs = st.executeQuery();

        if (rs.last()) {
          campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
        } else {
            JOptionPane.showMessageDialog(null, "Record not found");
            campusnametxt.setText("");
            campusnametxt.requestFocus();
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    } finally {

        try {
            if (st != null) {
                st.close();
            }
            if (con != null) {
                con.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
           
    }//GEN-LAST:event_LastbtnActionPerformed

    private void NextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextbtnActionPerformed
        // TODO add your handling code here:
        
    // TODO add your handling code here:

     try {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection(cs, user, password);
        st = con.createStatement();
        PreparedStatement st = con.prepareStatement("SELECT * FROM Campuses",
                ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        if (!bnext) {
            rs = st.executeQuery();
            rs.first();

          campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
            bnext = true;
        } else if (rs.next()) {

            campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
            bnext = true;

        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_NextbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        
    // TODO add your handling code here:

     // TODO add your handling code here:
    int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "confirm", JOptionPane.YES_NO_OPTION);

    if (answer == YES_OPTION) {
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            con = DriverManager.getConnection(cs, user, password);
            st = con.createStatement();

            PreparedStatement st = con.prepareStatement("DELETE  FROM Campuses WHERE   Campus_name ='" + campusnametxt.getText() + "'",
                    ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            if (st.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(null, "Record with Campus name: '" + campusnametxt.getText() + "'deleted");

            } else if (st.executeUpdate() == 0) {
                JOptionPane.showMessageDialog(null, "Record with Campus name: '" + campusnametxt.getText() + "'does not exist");
            }

                 campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
            campusnametxt.requestFocus();
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } finally {

            try {
                if (st != null) {
                    st.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

    } else if (answer == NO_OPTION) {
        campusnametxt.requestFocus();
        return;
    }

    }//GEN-LAST:event_DeletebtnActionPerformed

    private void PreviousbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousbtnActionPerformed
        // TODO add your handling code here:
        
    // TODO add your handling code here:

    // TODO add your handling code here:
    try {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection(cs, user, password);
        st = con.createStatement();

        PreparedStatement st = con.prepareStatement("SELECT * FROM Campuses",
                ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

        if (!bprevious) {
            rs = st.executeQuery();
            rs.last();

       campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
            bprevious = true;
        } else if (rs.previous()) {

 campusidtxt.setText(rs.getString("Campus_id"));
            campusnametxt.setText(rs.getString("Campus_name"));
            bnext = true;

        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    
}       
    }//GEN-LAST:event_PreviousbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Campuses().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Findbtn;
    private javax.swing.JButton Firstbtn;
    private javax.swing.JButton Lastbtn;
    private javax.swing.JButton Nextbtn;
    private javax.swing.JButton Previousbtn;
    private javax.swing.JTextField campusidtxt;
    private javax.swing.JTextField campusnametxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
